spring.datasource.url=jdbc:postgresql://localhost:5432/meu_banco?currentSchema=projeto_farmacia
spring.datasource.username=guilherme
spring.datasource.password=Guilherme123:@
spring.flyway.enabled=true
spring.flyway.schemas=projeto_farmacia

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true