spring.datasource.url=jdbc:postgresql://localhost:5432/meu_banco?currentSchema=projeto_farmacia
spring.datasource.username=postgres
spring.datasource.password=root
spring.flyway.enabled=true
spring.flyway.schemas=projeto_farmacia

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true